// <auto-generated />
namespace GerenciaIgreja.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Cria_Tabela_Funcao_Ministerial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Cria_Tabela_Funcao_Ministerial));
        
        string IMigrationMetadata.Id
        {
            get { return "201709230111592_Cria_Tabela_Funcao_Ministerial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
