// <auto-generated />
namespace GerenciaIgreja.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Incluindo_Required_Nome_FuncaoMinisterial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Incluindo_Required_Nome_FuncaoMinisterial));
        
        string IMigrationMetadata.Id
        {
            get { return "201709242326106_Incluindo_Required_Nome_FuncaoMinisterial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
